# Generated by Django 4.0.1 on 2022-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_rename_technical_notes_portfolioentry_notes_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioentry',
            name='ref',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
