# Generated by Django 4.0.1 on 2022-01-21 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_portfolioentry_ref_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='feedback',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='display.feedback'),
        ),
    ]
