# Generated by Django 4.0.1 on 2022-01-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_alter_portfolioentry_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioentry',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='display.technicalnote'),
        ),
        migrations.AlterField(
            model_name='section',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='display.portfolioentry'),
        ),
    ]
