# Generated by Django 4.0.1 on 2022-01-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_alter_portfolioentry_notes_alter_section_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioentry',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='portfolioentry',
            name='notes',
        ),
        migrations.AddField(
            model_name='feedback',
            name='entry',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.portfolioentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalnote',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.portfolioentry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='display.portfolioentry'),
            preserve_default=False,
        ),
    ]
